steps:
- name: gcr.io/cloud-builders/gcloud
  args: [
      'functions',
      'deploy','hello_world',
      '--region=us-west3'
      '--source=https://https://github.com/Kaushik-h/cloud-function/',
      '--trigger-http',
  ]
